#!/bin/bash

#set -x
#set -e

#
# Create additional, secondary initramfs image that we load in addition
# to the one contained on the Live ISO
#

TEMP=/tmp/.__initrdtmp

if [ $# -ne 1 ] ; then
  echo "Usage: $(basename $0) /path/to/Fedora-live.iso"
  exit 1
fi

if [ $UID -ne 0 ] ; then
  echo "You need to be root"
  exit 1
fi

mkdir "${TEMP}"
cd "${TEMP}"

mkdir -p ./usr/lib/dracut/hooks/pre-pivot/
cat > ./usr/lib/dracut/hooks/pre-pivot/30-deltadir.sh <<\EOF
#!/bin/sh

# Recursively link files into to the root of the live system
# Example:
# rd.live.deltadir=/run/initramfs/isoscan/boot/deltadir
# would recursively symlink the contents of /boot/deltadir 
# on the partition on which the ISO is located
# into / of the live system

DELTADIR=$(getarg rd.live.deltadir=)
cp -rsf "${DELTADIR}"/* /sysroot/
EOF
chmod a+x ./usr/lib/dracut/hooks/pre-pivot/30-deltadir.sh

echo "Repacking ${1}.initrd ..."
find . | cpio -o -H newc | gzip -9 > "${1}.addon"

cd - >/dev/null

rm -r "${TEMP}"
